import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Header from "../components/Header";
import Banner from "../components/Banner";
import SmallCard from "../components/SmallCard";
import MediumCard from "../components/MediumCard";
import LargeCard from "../components/LargeCard";
import Footer from "../components/Footer";

export default function Home({ exploreData, cardsData }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Setwork Online</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* Header */}
      <Header />

      {/* Banner */}
      <Banner />

      <main className="max-w-7xl mx-auto px-8 sm:px-16">
        <section className="pt-6">
          <h2 className="text-4xl font-semibold pb-5">Explore Nearby</h2>

          {/* Pull some data from a server - API endpoints 
          (This will change once Setwork users are connected) */}
          <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4">
            {exploreData?.map((item) => (
              <SmallCard
                key={item.id}
                img={item.img}
                name={item.name}
                job={item.job}
                location={item.location}
              />
            ))}
          </div>
        </section>
        <section>
          <h2 className="text-4xl font-semibold py-8">Discover Crew</h2>

          <div className="flex space-x-3 overflow-scroll scrollbar-hide p-3 -ml-3">
            {cardsData?.map((item) => (
              <MediumCard key={item.id} img={item.img} job={item.job} />
            ))}
          </div>
        </section>

        <LargeCard
          img="https://setwork.ai/images/1sa-p-1080.jpeg"
          title="hire filmmakers"
        />
      </main>

      <Footer />
    </div>
  );
}

{
  /* Dummy Data Fetch*/
}
export async function getStaticProps() {
  const exploreData = await fetch(
    "https://setwork.ai/new-site-data.json"
  ).then((res) => res.json());

  const cardsData = await fetch(
    "https://setwork.ai/new-site-data.json"
  ).then((res) => res.json());

  return {
    props: {
      exploreData,
      cardsData,
    },
  };
}
